### ISSUE TITLE
Also support file:// urls

### ISSUE THREAD

**Issue by vbraun** [oracle/cordova-plugin-wkwebview-file-xhr#1]
It would be nice if absolute file:// urls were also supported (checking that they point to a resource inside the www folder, of course). For example, the AngularJS template service makes XMLHttpRequest with absolute url to load templates, which then fail. Can be worked around on the Angular side, but would be nice if it worked out of the box.

Thanks for the great plugin!

**Comment by gvanmat** [comment]
Thanks for the feedback.

We are about ready to release another version of the plugin that works
around the "null" origin CORS header by handling remote XHR requests thru
the native layer too.  We will trying addressing the relative URL
limitation for local XHR in this release too.

Regards,
Gary

**Comment by vbraun** [comment]
I tried the implementation that has now hit the master branch and it works nicely for me!

**Comment by gvanmat** [comment]
Great!  We should be pushing out a public npm module soon - after finishing our internal testing.

**Comment by gvanmat** [comment]
Absolute file URLs were added in v2.0.0

**Comment by brunoborges** [comment]
Hey @gvanmat , mind to post link to change log?
