### ISSUE TITLE
this.response is undefined when responseType is a Blob/ArrayBuffer

### ISSUE THREAD

**Issue by Perroquiet** [oracle/cordova-plugin-wkwebview-file-xhr#11]
Hi I've tested this plugin in my case, a file object with a file url (from upload) and creating a Blob file of it through XHR: [MDN Link](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Sending_and_Receiving_Binary_Data)

```
var oReq = new XMLHttpRequest();
oReq.open("GET", "file:///myfile.png", true);
oReq.responseType = "blob";

oReq.addEventListener('loadend', function () {
    var res = this.response; // undefined
});

oReq.onload = function(oEvent) {
  var blob = oReq.response;
  // ...
};

oReq.send();
```

_**this.response**_ is always undefined. I've also checked _**this**_ with ajaxData attribute to be null. I'm not sure if Blob responseType is supported with this plugin but I'm also having a CORS exception when requesting to file:/// on a WKWebview.

**Comment by gvanmat** [comment]
A blob response type works fine but the issue is you are using an absolute URL.  The plugin will only allow access to files under the www folder of the application bundle (readonly).  If this image exists under the www folder, you can use a relative URL such as "./myfile.png" to load the image.
