### ISSUE TITLE
2.1.0 release

### ISSUE THREAD

**Issue by larssn** [oracle/cordova-plugin-wkwebview-file-xhr#12]
Hey, thanks for an amazing plugin. Has made our lives a lot easier in wkwebview-land.

Is v2.1.0 gonna go on npmjs? It seems you've fixed a critical bug from v2.0. :-)

**Comment by peppertech** [comment]
Thanks for the compliment @larssn .   We publish the Cordova plugins to the Cordova repository, but do not normally put them on npmjs as they are not installed using npm.

**Comment by larssn** [comment]
Ah sorry, brain fart on my part. I meant the cordova repo.

Doing an `cordova plugin add cordova-plugin-wkwebview-file-xhr` installs v2.0

**Comment by peppertech** [comment]
Right, got it.  We are looking for some verification from developers that have reported issues, and we've fixed, before we push the 2.1.0 release.  As soon as the release is pushed, we will definitely have it on the Cordova repos.

**Comment by larssn** [comment]
Alright, I'll keep my eyes open for any issues in v2.1. 👍
