### ISSUE TITLE
How to use with third-party software?

### ISSUE THREAD

**Issue by vortice3D** [oracle/cordova-plugin-wkwebview-file-xhr#16]
Hi there:

The case is that I'm using a webgl engine (BabylonJS) in one of my cross-platform developments.

My code loads textures, in the form of **PNG files**, using a specific API, like this:
```
texGeneric=new BABYLON.Texture("assets/textures/Generic.png",_Scene);
...
```
This works perfectly.

Also, I need to load a cube map/environment in the form of a **DDS file**, using this other API:
```
texEnvironment=BABYLON.CubeTexture.CreateFromPrefilteredData("assets/textures/environment.dds",_Scene);
```

This doesn't work.

Internally **CreateFromPrefilteredData** uses XHR, so when ported to a plain Cordova-iOS it can´t find the DDS file, as WKWebView appears to treat local files as if they came from a remote server, even though they're in the app itself, and such requests are blocked.

In this case I thought **cordova-plugin-wkwebview-file-xhr** could make it work but, when used, the app can't find the (previously working) local files as it output in the remote debug console from Safari:
Cross origin requests are only supported for HTTP.

I have also this relevant output in Xcode:
2018-04-02 12:15:30.245199+0200 GRB Technology[1165:700339] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
2018-04-02 12:15:30.248572+0200 GRB Technology[1165:700339] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service

Any clue on this? Do I need to add "http://" or something at the beginning of PNG paths?

Thanks for your time.

**Comment by gvanmat** [comment]
@vortice3D The cordova-plugin-wkwebview-file-xhr has a restriction of only allowing readonly access to files under the "www" folder of the applications bundle.  This is a signed secure part of the file system that cannot be altered once the application is installed.  Is the "asserts" folder located under "www" within the cordova application or is the file located on a remote endpoint?  

Try enabling "full" [plugin logging](https://github.com/oracle/cordova-plugin-wkwebview-file-xhr/blob/master/README.md#configuration ).  The logging is made to the JavaScript console log of the webview.

**Comment by vortice3D** [comment]
Hi **gvanmat**, and thank your for your time.

My folder tree is this:
www
  └-----/assets
  └-----/libs
  └-----/scripts
  └-----/styles
  └ index.html

Best regards.

**Comment by gvanmat** [comment]
@vortice3D  The file structure looks good.  You will need to enable full logging to give some insight into what's failing.

**Comment by vortice3D** [comment]
Well, **gvanmat**...excuse my lack of experience in this but, how can I enable such a "full" plugin login?

**Comment by vortice3D** [comment]
Excuse me. Wrong button!!

**Comment by gvanmat** [comment]
@vortice3D You need to edit your [config.xml](https://cordova.apache.org/docs/en/latest/config_ref/) found in the same root folder as www adding the following parameter:

`<preference name="NativeXHRLogging" value="full"/>`

**Comment by vortice3D** [comment]
Thanks gvanamt.

Is estrange, but the addition of the preference directive seems to do nothing, as I get the same remote console log than I got before (but not show in this thread):

[Error] XMLHttpRequest cannot load file:///var/containers/Bundle/Application/3685B4EA-BF39-4ABD-90B1-514825761447/GRB%20Technology.app/www/assets/models/Monomando.babylon.manifest?1522682768175. Cross origin requests are only supported for HTTP.
	checkManifestFile (babylon.3.1.custom.min.js:32:24533)
	t (babylon.3.1.custom.min.js:32:23392)
	_loadData (babylon.3.1.custom.min.js:32:2007)
	Append (babylon.3.1.custom.min.js:32:3894)
	_create (vortice3d.grb-bjs.js:121)
	Engine3D (vortice3d.grb-bjs.js:845)
	(función anónima) (grb.js:57)
[Error] XMLHttpRequest cannot load file:///var/containers/Bundle/Application/3685B4EA-BF39-4ABD-90B1-514825761447/GRB%20Technology.app/www/assets/models/Termostatico.babylon.manifest?1522682768176. Cross origin requests are only supported for HTTP.
	checkManifestFile (babylon.3.1.custom.min.js:32:24533)
	t (babylon.3.1.custom.min.js:32:23392)
	_loadData (babylon.3.1.custom.min.js:32:2007)
	Append (babylon.3.1.custom.min.js:32:3894)
	_create (vortice3d.grb-bjs.js:122)
	Engine3D (vortice3d.grb-bjs.js:845)
	(función anónima) (grb.js:57)
[Error] XMLHttpRequest cannot load file:///var/containers/Bundle/Application/3685B4EA-BF39-4ABD-90B1-514825761447/GRB%20Technology.app/www/assets/models/Monomando.babylon.manifest. Cross origin requests are only supported for HTTP.
	(función anónima) (babylon.3.1.custom.min.js:32:24505)
[Error] XMLHttpRequest cannot load file:///var/containers/Bundle/Application/3685B4EA-BF39-4ABD-90B1-514825761447/GRB%20Technology.app/www/assets/models/Termostatico.babylon.manifest. Cross origin requests are only supported for HTTP.
	(función anónima) (babylon.3.1.custom.min.js:32:24505)
[Error] XMLHttpRequest cannot load file:///var/containers/Bundle/Application/3685B4EA-BF39-4ABD-90B1-514825761447/GRB%20Technology.app/www/assets/models/Monomando.babylon. Cross origin requests are only supported for HTTP.
	h (babylon.3.1.custom.min.js:3:12095)
	LoadFile (babylon.3.1.custom.min.js:3:12366)
	_ (babylon.3.1.custom.min.js:32:1848)
	i (babylon.3.1.custom.min.js:32:23856)
	(función anónima) (babylon.3.1.custom.min.js:32:24514)
[Error] XMLHttpRequest cannot load file:///var/containers/Bundle/Application/3685B4EA-BF39-4ABD-90B1-514825761447/GRB%20Technology.app/www/assets/models/Termostatico.babylon. Cross origin requests are only supported for HTTP.
	h (babylon.3.1.custom.min.js:3:12095)
	LoadFile (babylon.3.1.custom.min.js:3:12366)
	_ (babylon.3.1.custom.min.js:32:1848)
	i (babylon.3.1.custom.min.js:32:23856)
	(función anónima) (babylon.3.1.custom.min.js:32:24514)
[Error] BJS - [17:26:08]: Unable to load from ./assets/models/Monomando.babylon: 0 
	(función anónima) (cordova.js:1731)
	_ErrorEnabled (babylon.3.1.custom.min.js:3:19303)
	c (babylon.3.1.custom.min.js:32:3794)
	(función anónima) (babylon.3.1.custom.min.js:32:1878)
	onreadystatechange (babylon.3.1.custom.min.js:3:12081)
[Error] BJS - [17:26:08]: Unable to load from ./assets/models/Termostatico.babylon: 0 
	(función anónima) (cordova.js:1731)
	_ErrorEnabled (babylon.3.1.custom.min.js:3:19303)
	c (babylon.3.1.custom.min.js:32:3794)
	(función anónima) (babylon.3.1.custom.min.js:32:1878)
	onreadystatechange (babylon.3.1.custom.min.js:3:12081)
[Error] ReferenceError: Can't find variable: nulll
	_createScene (vortice3d.grb-bjs.js:209)
	notifyObservers (babylon.3.1.custom.min.js:3:3626)
	_checkIsReady (babylon.3.1.custom.min.js:11:23164)
	(función anónima) (babylon.3.1.custom.min.js:11:23041)

The case is that this WebGL Engine uses a specific JSON file in order to describe scenes (meshes + lights + animations +...). In my code I have two of these JSONs, namely Monomando.babylon and Temostatico.babylon.

Well now (with the use of cordova-plugin-wkwebview-file-xhr) I can´t load them, but remember that before adding this plugin I could load them, and also the PNG textures, but not the CubeMap style DDS textures (as this last is loaded by the WebGL Engine using a XHR mechanism). This last issue was the problem who bring me to use cordova-plugin-wkwebview-file-xhr.

**Comment by gvanmat** [comment]
@vortice3D Sounds like you are going to need to do some debugging to determine why the cordova-plugin-wkwebview-file-xhr plugin is not being loaded.  It might also be that the babylon script library is loaded before the plugin-wkwebview-file-xhr plugin.  You should be able to attach the Safari browser to the application running in the XCode IDE.

**Comment by vortice3D** [comment]
I see.

In index.html I've just changed the <script src="cordova.js"></script> to a position before the <script src="libs/bjs/babylon.3.1.custom.min.js"></script>, but I get the same console output: 

(Excerpt)
"XMLHttpRequest cannot load file:///var/containers/Bundle/Application/E00CC1C9-7EB4-4828-826B-8270625C142C/GRB%20Technology.app/www/assets/models/Monomando.babylon.manifest?1522685023139. Cross origin requests are only supported for HTTP."

**Comment by vortice3D** [comment]
BTW, reviewing my config.xml file, I can see the line
`<plugin name="cordova-plugin-wkwebview-file-xhr" spec="^2.1.1" />`
, 
but nothing about the dependent **cordova-plugin-wkwebview**.

Anyway, the two are listed when a **cordova plugin list** is done.

**Comment by gvanmat** [comment]
@vortice3D I think the issue is the babylon APIs are using synchronous uses of XMLHttpRequest versus async.  I see places in the code like:

```
var i = new XMLHttpRequest;
i.open("get", r.href, false);
var s = i.responseText.replace....

```
The third argument [async](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/open#Parameters) has a value of "false".

The XMHttpRequest polyfill doesn't currently support synchronous calls.  However, it might be possible to implement with Safari 10.1 supporting [await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await).

**Comment by gvanmat** [comment]
@vortice3D The snippet of code I posted before is loading CSS. I don't think the images are loaded via XMLHttpRequest but rather some other technique using the browser. Whatever method is being used by this library to load images, it's not XMLHttpRequest or the Fetch API.

Unfortunately, fixing the synchronous send is not going to be a complete solution.

**Comment by gvanmat** [comment]
@vortice3D I debugged thru the babylon.js some and found the method it's using to load images. The method is [LoadImage](https://github.com/BabylonJS/Babylon.js/blob/master/src/Tools/babylon.tools.ts#L487).  They are creating an Javascript Image Object, setting the src to the target URI and adding "load" event listeners.  This would be outside the scope of the cordova-plugin-wkwebview-file-xhr.

**Comment by vortice3D** [comment]
Hi **gvanmat**:

First of all I wish to thank you very much your interest and support with this issue.

Ok, I know BJS is using that LoadImage API in order to "load the plain images", when I call **BABYLON.Texture** but as said I can load that textures (PNG files in my case) w/o problems under browser, Cordova-Android and Cordova-iOS platform.

The problems arises (only on Cordova-iOS), with the loading of environment textures, under the form of a DDS file, by means of **BABYLON.CubeTexture.CreateFromPrefilteredData**. BJS guys said me this behavior is because the engine is using an XHR loading mechanism in such a case.

Well, I'll let you know any advance on this.

Thanks for your time.

**Comment by gvanmat** [comment]
@vortice3D 

I was able to create a sample cordova ios app using the wkwebview-file-xhr plugin with a sample babylonJS app that uses BABYLON.SceneLoader.Load("textures/", "v8.babylon", engine, ...

The XMLHttpRequest polyfill provided by the plugin is intercepting the file:// GET requests.  I've attached a zip of the www folder of my project.  You might compare the script includes from index.html.


[www.zip](https://github.com/oracle/cordova-plugin-wkwebview-file-xhr/files/1873203/www.zip)

**Comment by vortice3D** [comment]
Hi Gary:

Thank for your collaborarion on all this.

I'll inspect your zip tomorrow and let you know.

Good night.

**Comment by vortice3D** [comment]
Hi again Gary:

I've seen your example of use.

Anyway your loading a .babylon file (scene) that is only a text file (JSON). I've not found problems loading local JSONs or local PNGs, but local DDS or MP3, as these two formats uses XHR in order to load the contents, if I host those DDS or MP3 in my server, and Ioad then from it in my code, then all works OK. But I'd prefer to have it stored locally, and so no external communications would be necessary for my app.

So this code does't work:
`var texEnvironment=BABYLON.CubeTexture.CreateFromPrefilteredData("assets/textures/environment.dds",_Scene);`

or this one:
```
var _Sfx=new BABYLON.Sound("sfx","assets/sounds/shower-sfx.mp3",_Scene,null,{
				autoplay: false,
				loop: true,
				volume: 0}
			);
```
 both don't work.

But changing to remote (served) content does work:
` var texEnvironment=BABYLON.CubeTexture.CreateFromPrefilteredData("http://www.vortice3d.com/private/environment.dds",_Scene);`
and so does also this one:
```
var _Sfx=new BABYLON.Sound("sfx","http://www.vortice3d.com/private/shower-sfx.mp3",_Scene,null,{
				autoplay: false,
				loop: true,
				volume: 0}
			);
```

**Comment by vortice3D** [comment]
BTW, reviewing your index.html I have another question on it, what are the meaning of these lines:
```
<meta http-equiv="Content-Security-Policy" content="default-src * data: *; style-src *; media-src *; img-src * data: * content: *;">
<meta name="format-detection" content="telephone=no">
<meta name="msapplication-tap-highlight" content="no">
```

Are they needed for Cordova-iOS apps?

**Comment by gvanmat** [comment]
@vortice3D The "Content-Security-Policy" controls what resources the browser can load such as img, style, script, and media.  XHR is invoked via JavaScript thru either the XMLHttpRequest or the Fetch API.  The plugin is a workaround for the CORS constraints for XHR (XMLHttpRequest and Fetch API) only.

If you debug the Babylon APIs, loading of the images **are not** going thru XHR.  They creating a [Image](https://github.com/BabylonJS/Babylon.js/blob/master/src/Tools/babylon.tools.ts#L496) object and assigning the src to the local resource.  I suspect the media is doing they same type of thing.  You might ask the Babylon guys if there is a way to form the URL so the local resource can be loaded via XHR.  I think if you use [file://](https://github.com/BabylonJS/Babylon.js/blob/master/src/Tools/babylon.tools.ts#L535) it will load the resource using the File API and assign the image as a data url of the image, which would mean you would need the cordova-plugin-file.

One more point on the wkwebivew-file-xhr plugin, by default only secure "https" remote calls are intercepted.  You have to set the [InterceptRemoteRequests](https://github.com/oracle/cordova-plugin-wkwebview-file-xhr/blob/master/README.md#configuration) preference to "all".

Please also note that in the sample I provided where loading the v8.babylon file is being intercepted by the wkwebview-file-xhr plugin, the babylon script is not invoked until the device is ready.  See the /js/index.js.  If you are not already doing this, you will want to wait for cordova to be ready before running additional scripts.

**Comment by vortice3D** [comment]
Hi **Gary**:

I agree with you in the way BJS is loading contents, standard image files are managed through an Image, but other (binary) types needs to use Ajax calls (XHR) as no one HTML-DOM element can load it.

Asking the BJS guys about this issue they are saying me it's a bug of Cordova with local XHR (and that's the reason I got initially to this Cordova plugin).

I've tried the "cordova-plugin-file" + "file://" combination w/o success:
```
018-04-04 16:30:06.144685+0200 GRB Technology[1540:1057567] NSURLConnection finished with error - code -1100
2018-04-04 16:30:06.151657+0200 GRB Technology[1540:1057326] ERROR: BJS - [16:30:06]: error on XHR request.
```

Well, I really appreciate your support on this, but as I do not wish to take more time from you, and this is "not-a-really-this-plugin-issue" (but Cordova's one) I think the best is to close the issue.

Thanks.

**Comment by gvanmat** [comment]
The MP3 load issue is likely because the babylon code is not setting the XMLHttpRequest [responseType](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType) to "arraybuffer".  The polyfill with this plugin only has a small list of file suffixes to default response types.  The native XMLHttpRequest probably defaults "arraybuffer" based on the URL suffix but we are defaulting to text.

**Comment by vortice3D** [comment]
Hi Gary:

Only if this info can be useful to you or somebody else, I've asked BJS staff about your thoughts on the responseType on XHR call for:
BABYLON.Sound("sfx","assets/sounds/sfx.mp3",_Scene,null,{
  autoplay: false,
  loop: true,
  volume: 0}
);

and they've answered that's weirds, as "...because we ARE actually setting the responseType to arrayBuffer: https://github.com/BabylonJS/Babylon.js/blob/c224954e1b2005f1d01fa711904075e0129a208e/src/Tools/babylon.tools.ts#L604"
