### ISSUE TITLE
Screen change orientation bug

### ISSUE THREAD

**Issue by vortice3D** [oracle/cordova-plugin-wkwebview-file-xhr#17]
Hi there:

When a change the orientation of my device (iPad Mini running **iOS 11.2.6**) wkwebview doesn't cover the entire height of screen.

That is, when the WKWebView is used, rotating the screen doesn't trigger a resize of the HTML, but it works correctly with UIWebView.

It's possible to "hack" this behavior firing a temporized **_window.dispatchEvent(new Event('resize')_**, but I find it clumsy as it involves a Race Condition.

Maybe it has to be with this code in **Xcode**?:

`CGRect screenBounds = [[UIScreen mainScreen] bounds];
self.window = [[UIWindow alloc] initWithFrame:screenBounds];
self.window.autoresizesSubviews = YES;`

Any help on this?

**Comment by vortice3D** [comment]
About this issue, searching more in deep over the web, I see different related posts:

- `https://stackoverflow.com/questions/35042412/wkwebview-displays-content-wrong-after-orientation-change`
- `https://stackoverflow.com/questions/3778552/auto-resize-subviews-on-device-rotation`

So well this seems to be a problem related with the iOS autoresizingMask. Anyway I see it is set OK in my CDVViewController.m file:

`(void)createGapView
{
    CGRect webViewBounds = self.view.bounds;

    webViewBounds.origin = self.view.bounds.origin;

    UIView* view = [self newCordovaViewWithFrame:webViewBounds];

    view.autoresizingMask = (UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight);
    [self.view addSubview:view];
    [self.view sendSubviewToBack:view];
}`

**Comment by Hirbod** [comment]
You are in the wrong repo my friend. This one here is only fixing XHR issues, you should send your message to the webview maintainers.

https://github.com/apache/cordova-plugin-wkwebview-engine
https://github.com/ionic-team/cordova-plugin-ionic-webview

**Comment by vortice3D** [comment]
Ok man, I'll do so.

I came to this plugin looking for an xhr solution so I didn't notice at all there was a cordoba-plugin-wkwebview dependency.

Best regards.

**Comment by Hirbod** [comment]
Fyi, you have to post your issues here:
https://issues.apache.org/jira/browse/CB-12074?jql=project%20%3D%20CB%20AND%20status%20%3D%20Open%20AND%20labels%20%3D%20wkwebview-known-issues
