### ISSUE TITLE
Works on simulator but not on device for file prot

### ISSUE THREAD

**Issue by gertgjoka** [oracle/cordova-plugin-wkwebview-file-xhr#19]
Hello,

thanks for the work with this plugin!
I have an issue, when running the app on the simulator from xcode it works fine with local file:// resources, but when I debug on my device it doesnt work and fails with the following: 
Failed to load resource: The operation couldn’t be completed. Operation not permitted
file:///var/mobile/Containers/Data/Application/B01D6417-EC0C-49D4-9B80-6EC64C2500D6/Library/NoCloud/134816086487-7927-4917-9d8d-8fb72ede76c6.jpg
[Error] Failed to load resource: The operation couldn’t be completed. (kCFErrorDomainCFNetwork error 1.)

**Comment by gvanmat** [comment]
@gertgjoka The plugin has a restriction that it can only read local files contained within the application bundle.  This resource is located at "Library/NoCloud/134816086487-7927-4917-9d8d-8fb72ede76c6.jpg". I would expect to see "www" in the path.  Please verify this resource exists under the application bundle and is loaded via XMLHttpRequest or Fetch API?

**Comment by gertgjoka** [comment]
@gvanmat Thanks for the reply. No this is a file the app is downloading as an avatar of the user profile, so not part of the bundle. Isn't there a way to set a local downloaded file as an src of an image?

**Comment by gvanmat** [comment]
@gertgjoka  The document running in the webview is loaded from the "www" folder.  The browser will allow you to load resources under the root folder from where the document was loaded but will not allow access to other parent folders or file systems.  You would need to use the cordova-plugin-file to load the content.  Maybe you could load using the file plugin and convert the image to a data URL?

**Comment by gertgjoka** [comment]
@gvanmat Thanks for the tips! Cheers

**Comment by sirius2013** [comment]
@gertgjoka I got same problem. can you help for this?
![permission-error-load-file](https://user-images.githubusercontent.com/5020713/49035025-a3df3b00-f1c4-11e8-9eed-4fe4a93e0852.png)
![permission-error-3](https://user-images.githubusercontent.com/5020713/49035026-a5a8fe80-f1c4-11e8-9545-f325fa55d874.png)

**Comment by akbarsha03** [comment]
> @gvanmat Thanks for the tips! Cheers

Hi Gvanmat, Need help here, Facing the same issue. In my case I don't use Cordova, I'm using react to render where I'm trying to show an image. Any suggestions, please?

**Comment by BrianCortes** [comment]
Hi @gvanmat I am having the same error in my simulator is working but on device with this url  file:///var/mobile/Containers/Data/Application/6DCD480A-7283-4697-938E-52CCB43E2B1A/Library/files/a68c1c5c-1585-41ce-a5aa-693d5db41ac3.png I get this Failed to load resource: The operation couldn’t be completed. Operation not permitted

I am using those plugin: 
- cordova-plugin-wkwebviewxhrfix
- cordova-plugin-wkwebview-file-xhr

**Comment by csantanu** [comment]
> Hi @gvanmat I am having the same error in my simulator is working but on device with this url file:///var/mobile/Containers/Data/Application/6DCD480A-7283-4697-938E-52CCB43E2B1A/Library/files/a68c1c5c-1585-41ce-a5aa-693d5db41ac3.png I get this Failed to load resource: The operation couldn’t be completed. Operation not permitted
> 
> I am using those plugin:
> 
> * cordova-plugin-wkwebviewxhrfix
> * cordova-plugin-wkwebview-file-xhr

Yes, me too facing the same issue and I reported this in a new issue few minutes back.
