### ISSUE TITLE
Shared iOS Folders

### ISSUE THREAD

**Issue by sorny** [oracle/cordova-plugin-wkwebview-file-xhr#2]
This plugin works fine when accessing files within the read-only www application dir as mentioned in the readme.

The plugin cordova-plugin-file (https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/) supports file-writing to an application-specific read/write space.

Shouldn't the security check focus on the container base path? Or make the security check configurable?

Example:

Current security check on read-only ww dir: /var/containers/Bundle/Application/9579B5BA-ED95-4D9E-AF6D-3524725791CE/HelloWorld.app/www

Proposed: /var/containers/Bundle/Application/9579B5BA-ED95-4D9E-AF6D-3524725791CE

**Comment by gvanmat** [comment]
The plugin isn't meant to replace cordova-plugin-file.  Currently, it constrains GET requests to the application bundle.

The application bundle is part of the base cordova strategy for distributing web resources.  Anything outside of this readonly space could be a security vulnerable.

**Comment by sorny** [comment]
Could you explain the imposed security vulnerabilities a little bit further?

**Comment by gvanmat** [comment]
The [application bundle](https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html) is readonly.  It is signed at install time.  Tampering with it will change its signature result in the application not launching.  This is the location web resources are package for consumption by the webview in a Cordova hybrid mobile application.

Allowing access outside this secure area could result in Directory Traversal Attacks.
