### ISSUE TITLE
Doesn't seem to interop with the firebase sdk

### ISSUE THREAD

**Issue by larssn** [oracle/cordova-plugin-wkwebview-file-xhr#20]
Feel free to close if this is outside the scope of the project.

We're using the firebase sdk (https://github.com/firebase/firebase-js-sdk) in a cordova project, and when this plugin is added, all communication to their remote server seems to be blocked.

They are using xhr internally in the framework already.

**Comment by gvanmat** [comment]
@larssn Integration with firebase-js-sdk has never been tested but in theory it should work.  What types of errors are you seeing on the JS console?  You can enable plugin logging using the "NativeXHRLogging" [preference](https://github.com/oracle/cordova-plugin-wkwebview-file-xhr#configuration) with a value of "all".

My best guess is that you are not using secure protocol with the firebase sdk.  By default, the wkwebview-file-xhr plugin will only intercept https traffic.  You can use the "InterceptRemoteRequests" [preference](https://github.com/oracle/cordova-plugin-wkwebview-file-xhr#configuration) set to "all" to intercept http traffic too.

It could also be you are using a secure protocol but your rest endpoint has a self signed certificate.  Use the "AllowUntrustedCerts" [preference](https://github.com/oracle/cordova-plugin-wkwebview-file-xhr#configuration) set to "on" to allow these requests to complete.

**Comment by larssn** [comment]
We ended up using https://github.com/silkimen/cordova-plugin-advanced-http against the relevant services. We're cautious about plugins that override native functionality.

Sorry for the inconvenience. Gonna close this.

**Comment by gvanmat** [comment]
@larssn Totally understand not wanting to override native functionality.  If you have the option of isolating iOS application resources from other supported mobile platforms you might support, that seems the way to go.

**Comment by MatthewPringle** [comment]
I have just had a similar issue.

When using aws-sdk the response from the server / aws is blocked and causes aws-sdk to error.

.createPlatformEndpoint() is the function im using.

Removing the plugin and it all works file.

**Comment by gvanmat** [comment]
@MatthewPringle  Are you seeing any errors?  Have you tried enabling [plugin logging](https://github.com/oracle/cordova-plugin-wkwebview-file-xhr#configuration)?

**Comment by MatthewPringle** [comment]
@gvanmat 

The amazon library throws this error "TypeError: undefined is not an object (evaluating 'resp.httpResponse.body.toString')"

Having enabled logging I can see the response and it all looks fine, no error codes or anything.

The mimeType is text/xml though, which is different from all my other requests that work fine and are application/json.

**Comment by gvanmat** [comment]
@MatthewPringle  It sounds like the [responseType](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType) is not being set to "document"?

**Comment by MatthewPringle** [comment]
@gvanmat thats going to be something thats buried deep in the aws-sdk.js
