### ISSUE TITLE
XHR local file request throwing cross origin error

### ISSUE THREAD

**Issue by rsj296** [oracle/cordova-plugin-wkwebview-file-xhr#23]
I realise this has been asked and closed in the previous issues. However, I'm still unable to get this plugin to work after a few hours of going through all the threads. Error details and my environment below:

[Error] XMLHttpRequest cannot load file:///Users/user001/Library/Developer/CoreSimulator/Devices/B928C8B2-1A44-488F-93D6-0039C51CF17F/data/Containers/Bundle/Application/6047BE0D-F397-4105-A6E9-F3B9F8492413/MobileApp.app/www/pages/home.html. Cross origin requests are only supported for HTTP.
	testXHR (index.html:112)
	onclick (index.html:53)

```
function testXHR(){
            var xhr = new XMLHttpRequest();
            xhr.addEventListener("loadend", function(evt)
            {
            var data = this.responseText;
            console.log(data);
            });
            
            xhr.open("GET", "pages/home.html");
            xhr.send();
}
```

 engine name="ios" spec="^4.5.4" 
 plugin name="cordova-plugin-wkwebview-engine" spec="^1.1.4" 
 plugin name="cordova-plugin-wkwebview-file-xhr" spec="^2.1.1" 
  
IOS : 11.4 running on iPhone 8, 8P, IphoneX simulators and IphoneX device.
Xcode : 9.4.1

**Comment by gvanmat** [comment]
@rsj296 Are you waiting for the cordova ready event to fire before sending the request?  It sounds as if the plugin polyfill  (wkwebview-file-xhr plugin) has not been loaded yet.  Are you seeing any other JS or iOS console messages?  What other cordova plugins are you also using?

**Comment by gvanmat** [comment]
@rsj296 I'm not seeing the reported issue when running the tests on iphone 8 from the simulator.  It sounds like something is preventing the wkwebview-file-xhr plugin from loading or you are not waiting for the [deviceready](https://cordova.apache.org/docs/en/4.0.0/cordova/events/events.deviceready.html) event before sending an XHR request.  Please reopen if you have more information.

**Comment by rsj296** [comment]
@gvanmat you were right on the money! I have edited by code to ensure the xhr calls are made only after deviceready is fired and it is working great. Thanks for pointing it out.
