### ISSUE TITLE
cordova /Library/NoCloud/ and /Library/files

### ISSUE THREAD

**Issue by marc0n3** [oracle/cordova-plugin-wkwebview-file-xhr#27]
I see the plugin is limited to www.
Should it not be limited to the whole app directories that are user writable?

Is there a way I can use it to read those files?

Thanks in advance

**Comment by gvanmat** [comment]
No, the intention is not to provide greater access outside the protection of the readonly application bundle.  Access outside the www folder defining the document root would open up to a directory traversal attack.

**Comment by marc0n3** [comment]
Thank you, I'll try other ways.

Best regards,
Marco

**Comment by gvanmat** [comment]
@marc0n3  You might look at using the [file plugin](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/).

**Comment by marc0n3** [comment]
Sorry, one more thing.
Actually, in cordova, I've access to dataDirectory, syncedDataDirectory, cacheDirectory, that resides in the Library folder of the app.
Why can't i read a file that I've stored in dataDirectory, for example an image?
Actually I've access to these file using cordova-file plugin, but on android I still can call the file using the path.
I don't understand why the same thing is not possible under WkWebView using your plugin by allowing access to the list of dir listed here: https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/#ios-file-system-layout (https://link.getmailspring.com/link/1538755532.local-0a72e336-820b-v1.4.2-f587b7b7@getmailspring.com/0?redirect=https%3A%2F%2Fcordova.apache.org%2Fdocs%2Fen%2Flatest%2Freference%2Fcordova-plugin-file%2F%23ios-file-system-layout&recipient=cmVwbHkrMDBjNDAzN2Y1ZDEyODk0M2E3ZmJkMjI3MzMxY2FiNmFhZTc1M2YwNzY4NDU5NjQ3OTJjZjAwMDAwMDAxMTdjZjRiODI5MmExNjljZTE1ZTNmNjY5QHJlcGx5LmdpdGh1Yi5jb20%3D)
I'm looking at a way to load the data from XHR because I've a proprietary solution similar to CodePush that load my application in file:///var/mobile/Containers/Data/Applocation/XXXXXXXXXXXXX/Library/files/ and stores user generated files in file:///var/mobile/Containers/Data/Applocation/XXXXXXXXXXXXX/Library/NoCloud
Apple Store is not my concern because I release inHouse, so there are any other security issue you see if i enable those dirs by forking your plugin?

**Comment by sirius2013** [comment]
@marc0n3  Did you solve problem? because I got same issue now
![permission-error-3](https://user-images.githubusercontent.com/5020713/49035488-ff5df880-f1c5-11e8-9a41-aaea76d01d1d.png)
![permission-error-load-file](https://user-images.githubusercontent.com/5020713/49035490-008f2580-f1c6-11e8-804d-461873e48fd4.png)

**Comment by marc0n3** [comment]
@sirius2013  I've abandoned the search! 
There were too many issues in the loading process we've done and we opted for a "local server on the phone" solution.
Good luck!

**Comment by sajallimbu** [comment]
> @marc0n3 Did you solve problem? because I got same issue now
> ![permission-error-3](https://user-images.githubusercontent.com/5020713/49035488-ff5df880-f1c5-11e8-9a41-aaea76d01d1d.png)
> ![permission-error-load-file](https://user-images.githubusercontent.com/5020713/49035490-008f2580-f1c6-11e8-804d-461873e48fd4.png)

Did you find a solution to this? I've been trying to solve this and have looked for some work arounds but i really dont want to copy files in temp or opt for a "local server on the phone" solution.

**Comment by marc0n3** [comment]
@sajallimbu Sorry, but no. I've abandoned the task
