### ISSUE TITLE
iOS 12 svg as background getting Origin null

### ISSUE THREAD

**Issue by globules-io** [oracle/cordova-plugin-wkwebview-file-xhr#29]
My svg's as background-image in css are not loading
I used 
```
<preference name="InterceptRemoteRequests" value="all" />
<plugin name="cordova-plugin-wkwebview-engine" spec="^1.1.4" />
<plugin name="cordova-plugin-wkwebview-file-xhr" spec="^2.1.1" />
```
Still getting not allowed due to Origin null over file:///var/containers/Bundle/Application/....
cordova iOS 5.0.0
cordova 7.1
Any help appreciated

**Comment by globules-io** [comment]
As a work around, I've handled my svg's in css as url('data:image/svg...');

**Comment by gvanmat** [comment]
The plug-in can only intercept xMLHttpRequest and fetch API. It's not able to intercept resources resolved in html but the browser such as images. The standard rules still apply for these. They must be located under the context root (www folder in application bundle)

**Comment by globules-io** [comment]
My understanding is that it was handling all calls made to file:// 

"The default behavior of WKWebView is to raise a cross origin exception when loading files from the main bundle using the file protocol - "file://". This plugin works around this shortcoming by loading files via native code if the web view's current location has "file" protocol and the target URL passed to the open method of the XMLHttpRequest is relative. "

My SVGs all load fine but the ones specified in CSS files which are of course inside www as well as the SVGs. When the CSS file is applied, the request is made to load the SVG (as background-image) to file:///var/containers/Bundle/Application/[...]/mySVG.svg and then I get the "not allowed due to Origin null".

**Comment by gvanmat** [comment]
The plug will not override how the browser resolves CSS and HTML resources. It only intercept xhr (https://en.m.wikipedia.org/wiki/XMLHttpRequest) traffic. Xhr is handled within the JavaScript context. Xhr can load files from the application bundle via the file:// protocol or remote resources. It can't intercept how the webview resolves resources outside xhr.

**Comment by globules-io** [comment]
OK thanks.

**Comment by lehizojie** [comment]
@globules-io Please did you ever resolve this issue? I am having the same problem.

**Comment by globules-io** [comment]
@lehizojie yes, via https://github.com/globules-io/cordova-plugin-wkwebviewxhrfix

**Comment by lehizojie** [comment]
> @lehizojie yes, via https://github.com/globules-io/cordova-plugin-wkwebviewxhrfix

Thanks!!! This worked.

**Comment by lovelyelfpop** [comment]
Use this plugin https://github.com/communico/cordova-httpd to start a local server inside app
```
cordova.plugins.CorHttpd.startServer({
    'www_root': cordova.file.dataDirectory.replace( 'file://', '' ),
    'port': 8080,
    'localhost_only': false
}, function( url ){
    // eg. http://10.0.0.185:8080/
    // if localhost_only is true，then url is http://127.0.0.1:8080/
    console.log(url);
}, function( error ){
    console.log(error);
});
```
For example, if a file path looks like：
file:///data/user/0/com.pushsoft.aio5app/files/image/7c8f2985-01b3-4fd2-ad7b-f39812a920a2

you can use this url to show the image：
http://127.0.0.1:8080/image/7c8f2985-01b3-4fd2-ad7b-f39812a920a2

**Comment by globules-io** [comment]
cordova-ios +6 compatible
https://github.com/globules-io/cordova-plugin-ios-xhr
