### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by medslt** [oracle/cordova-plugin-wkwebview-file-xhr#3]
Hello,

I added this plugin to my Cordova project to fix the following issue:

```
XMLHttpRequest cannot load file:///var/containers/Bundle/Application/51326CDD-4449-480E-908C-2E4CC131F0E1/Example%20app.app/www/app/dist/img/sprite.svg. Cross origin requests are only supported for HTTP.
```

Even after I added this plugin and build my app again the issue isn't resolved.

Is this plugin intended to fix this kind of issue?

Thank you,

**Comment by gvanmat** [comment]
Yes, the plugin should solve this issue.  However, the plugin only supports wkwebview for iOS.  What version of the plugin are you using?

**Comment by gvanmat** [comment]
No followup in several weeks.  Closing the issue.

**Comment by vortice3D** [comment]
Hi **gvanmat**:

First of all, excuse for re-open an already closed issue thread but I've got this same question of **medslt**.

The case is that I'm using a webgl engine (BabylonJS) in one of my cross-platform developments.

My code loads textures, in the form of **PNG files**, using a specific API, like this:
```
texGeneric=new BABYLON.Texture("assets/textures/Generic.png",_Scene);
...
```

Also, I need to load a cube map/environment in the form of a **DDS file**, using this other API:
`texEnvironment=BABYLON.CubeTexture.CreateFromPrefilteredData("assets/textures/environment.dds",_Scene);`

This last API (CreateFromPrefilteredData) uses XHR, so when ported to a plain Cordova-iOS it can´t find the DDS file.

I think this plugin (cordovan-plugin-wkwebview-file-xhr) could make it work but when I use it the app can´t find even the (previously working) PNGs.

Any clue on this?

Thanks for your time.
