### ISSUE TITLE
Script in head do not load

### ISSUE THREAD

**Issue by yoldar** [oracle/cordova-plugin-wkwebview-file-xhr#38]
I have simple script tag in head

`<script src="https://cdn.announcekit.app/widget.js"></script>`

When I start app I got message "An error occurred trying to load the resource" in console.

Does anybody know how to fix it?

Thanks!

**Comment by gvanmat** [comment]
It sound like your cdn doesn't support cross origin requests. What type of error do you see on the J's console?

**Comment by manish2788** [comment]
No response!! Closing the issue.

**Comment by snehasis** [comment]
It should load from CDN without any Issue. CDNs are used cross origins.

You can try adding this if not working
<access origin="*://*/*" />
