### ISSUE TITLE
Plugin not intercepting eventSource or calls from html

### ISSUE THREAD

**Issue by cszasz** [oracle/cordova-plugin-wkwebview-file-xhr#40]
It seems that although I set the InterceptRemoteRequests to all
<preference name="InterceptRemoteRequests" value="all" />
calls not created directly by an ajax call is not intercepted.
As a result eventSource or an img will fail if authentication (cookies) is required.

Is this intentional, or I am missing something.
Currently my workaround is that I initiate a login also by a non intercepted call so I set up the session cookies in both layers.

Also I couldn't make that the origin not to be "null" while according to the documentation this one important feature.

I cannot say that cordova-plugin-wkwebview-file-xhr doesn't do anything either as without the plugin I cannot make any calls because my server needs the AllowUntrustedCerts=on setting, which seems to work. Strange...

Is my configuration correct?
    <feature name="CDVWKWebViewEngine">
         <param name="ios-package" value="CDVWKWebViewEngine" />
    </feature>
    <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
    <preference name="AllowUntrustedCerts" value="on" />
    <preference name="InterceptRemoteRequests" value="all" />
    <plugin name="cordova-plugin-wkwebview-engine" spec="^1.2.1">
    </plugin>
    <plugin name="cordova-plugin-wkwebview-file-xhr" spec="^2.1.1"/>

**Comment by gvanmat** [comment]
XHR is isolated to the JavaScript context - XMLHttpRequest and fetch API. The plug-in can't intercept how the browser retrieves images defined by the DOM. Bypassing self signed certificates is also isolated to XHR. Please see the known limitation section of the readme regarding cookie handling.

As a workout, you could fetch images via XHR and convert them to data urls.

**Comment by cszasz** [comment]
That was my guess as well, but then, why does have the plugin any effect regarding the self signed certificates? Is the XHR calls are isolated from the WKWebView plugin as well?

My workaround was that on iOS (and only there) injected a login url into the html, which this way retrieved the required session cookies and then was able to download the images correctly.
The same applies to the logout procedure. This workaround seemed to me better as apart from the login and logout the rest of the code remained unchanged after I changed to WKWebView.
