### ISSUE TITLE
Double encodeURI UTF-8 params

### ISSUE THREAD

**Issue by yoldar** [oracle/cordova-plugin-wkwebview-file-xhr#41]
Hi! Thanks for great plugin!

I noticed that when there is UTF-8 parameter value string it makes encodeURI twice.
How to fix this? Thanks!

<img width="1133" alt="Screen Shot 2019-08-05 at 14 43 07" src="https://user-images.githubusercontent.com/1597578/62451460-24acf880-b790-11e9-962f-aa1f21fe8221.png">

**Comment by nateweldon** [comment]
We are using this plugin and we have noticed this issue as well. Our team did some digging and it looks like the following commit caused the issue. 

[https://github.com/oracle/cordova-plugin-wkwebview-file-xhr/commit/3af1d4cf38bd484492433e97e1688bc57569a292](3af1d4cf38bd484492433e97e1688bc57569a292)


This change escapes the URLs given to the XHRs by calling stringByAddingPercentEncodingWithAllowedCharacters:NSCharacterSet.URLQueryAllowedCharacterSet
This will result in a double encoded URL. 

Documentation around this says that this will cause double encoding if a string is all ready percent-encoded.  

[https://developer.apple.com/documentation/foundation/nsstring/1411946-stringbyaddingpercentencodingwit?language=objc](url)

**Comment by manish2788** [comment]
@yoldar @nateweldon We are currently working to get this resolved, will be pushing the fix soon.

**Comment by manish2788** [comment]
@yoldar @nateweldon Did you guys used the latest plugin released at NPM ?

**NPM** : https://www.npmjs.com/package/cordova-plugin-wkwebview-file-xhr

If you take the plugin from npm and use it in your app, you should not face the mentioned issue.

Plugin at Github over here contains few unreleased changes which we will be pushing with next release.

We will revert following commit to fix the issue reported

https://github.com/oracle/cordova-plugin-wkwebview-file-xhr/commit/fcaed644fbb81e9f02f0e3e93b7f6d1c9a27da08#diff-eac12baadc3e2716cfcde96eb25bc4cc

**Comment by nateweldon** [comment]
@manish2788. No, we forked the repo and reverted the following commit. 

[https://github.com/oracle/cordova-plugin-wkwebview-file-xhr/commit/fcaed644fbb81e9f02f0e3e93b7f6d1c9a27da08#diff-eac12baadc3e2716cfcde96eb25bc4cc](url)

We ran into another issue with multipart file upload on IOS only. We are working through submitting a new PR the oracle/cordova-plugin-wkwebview-file-xhr to fix this.

**Comment by noahcooper** [comment]
@nateweldon what is the issue you're experiencing with multipart/form-data requests on iOS, and what was your fix? I have ongoing problems with multipart requests that I cannot solve -- on iOS only, my requests result in the network connection being lost.

**Comment by ruisalgado** [comment]
@manish2788 any word on that commit reversal? Just bumped into this same double encoding issue

**Comment by manish2788** [comment]
@ruisalgado Hi Rui, We have reverted the commit fcaed644fbb81e9f02f0e3e93b7f6d1c9a27da08 to resolve the reported issue of Double encodeURI UTF-8 params. Change is now available in master branch.

**Comment by noahcooper** [comment]
@manish2788 will you be bumping the version and publishing to npm?

**Comment by manish2788** [comment]
@noahcooper Yes Noah, In next step I will be publishing the updated version of the plugin over npm.

**Comment by jacobweber** [comment]
Thanks! This just bit us as well.

**Comment by noahcooper** [comment]
Any update on getting this updated on npm?

Also, it looks like the current version on npm is 2.1.2, but package.json here is 2.1.1.

**Comment by manish2788** [comment]
@noahcooper Hi Noah, We will be releasing the updated version of plugin to npm by 21st of November.

**Comment by manish2788** [comment]
@noahcooper Latest plugin version (2.1.3) has been released to npm
