### ISSUE TITLE
A similar plugin for Android?

### ISSUE THREAD

**Issue by haveamission** [oracle/cordova-plugin-wkwebview-file-xhr#43]
I am also seeing CORS issues on the latest versions of Android.

Is there a possibility that we might see this plugin for Android as well?

**Comment by peppertech** [comment]
wkwebview is an iOS library.  It is not something that is available or used in Android.

**Comment by haveamission** [comment]
I know that. I am asking if something similar could be made for Android's Chrome.

It's essentially a feature request

**Comment by haveamission** [comment]
Oh nevermind, this is made by Oracle. It's not likely they'll make a random fix for Chrome too. Sorry about that.

**Comment by kluverua** [comment]
Did you manage to find an analogue for Android?
