### ISSUE TITLE
How to load file:// images in Cordova iOS platform?

### ISSUE THREAD

**Issue by SiavashBamshadnia** [oracle/cordova-plugin-wkwebview-file-xhr#44]
Hi!
Please answer my question on stackoverflow:
https://stackoverflow.com/questions/57926513/how-to-load-file-images-in-cordova-ios-platform
Thanks.

**Comment by gvanmat** [comment]
The images can only be read from the www folder of the applications bundle.

**Comment by sbamtr** [comment]
Thanks for your attention, @gvanmat !
You mean there ins't any way to show images in app data on WKWebView?

**Comment by gvanmat** [comment]
Images must be located under the context root if served from the local
device. The context root I where the index.html page lives which is the app
bundle and www folder. This is no different than standard web development.
Images loaded from under the subtree where the document is loaded is from
self. Images loaded from a different domain are cross origin.

**Comment by lovelyelfpop** [comment]
The images under `file:///var/mobile/Applications/Container/Data/<GUID of app>/tmp/` can be loaded, it's not a cross origin issue, it's just apple don't let you display images located on anywhere Else

**Comment by gvanmat** [comment]
Using this plug-in, you can load resources from any location under the applications bundle www folder using xhr. The target resources must be under the folder from where the index.html is loaded.

**Comment by ramgrg** [comment]
Isn't it possible through base64?

**Comment by lovelyelfpop** [comment]
Base64 causes OOM

**Comment by sajallimbu** [comment]
So is there a fix to load images from file:// ? I can load images by copying them in temp but this causes issues with memory when loading more images and some features that require to get images whenever a certain page is loaded.

**Comment by peppertech** [comment]
This is not something that can be "fixed"  It is a security issue to be able load files outside of the app root.  It will not be enabled.  As @gvanmat said in an earlier answer:

**Comment by mgoetz85** [comment]
So just to make sure I got this right:
there is no chance to save an image in e.g. NoCloud dataDirectory and show it in an <img /> tag?

**Comment by ragcsalo** [comment]
Can you write an example code of loading a local image (from the www/img folder) to a HTML5 canvas element, and getting the image data without getting a CORS error?  Now I use this code, which loads the image just fine:

`img.src = cordova.file.applicationDirectory+'www/img/image.png';`

But when I try to access the image data using `ctx.getImageData()` I still get a CORS error.
Also if I use the crossorigin attribute `img.crossOrigin = 'Anonymous';` then the image won't load at all...

**Comment by lovelyelfpop** [comment]
Use this plugin https://github.com/communico/cordova-httpd to start a local server inside app
```
cordova.plugins.CorHttpd.startServer({
    'www_root': cordova.file.dataDirectory.replace( 'file://', '' ),
    'port': 8080,
    'localhost_only': false
}, function( url ){
    // eg. http://10.0.0.185:8080/
    // if localhost_only is true，then url is http://127.0.0.1:8080/
    console.log(url);
}, function( error ){
    console.log(error);
});
```

For example, if a file path looks like：
file:///data/user/0/com.pushsoft.aio5app/files/image/7c8f2985-01b3-4fd2-ad7b-f39812a920a2

you can use this url to show the image：
http://127.0.0.1:8080/image/7c8f2985-01b3-4fd2-ad7b-f39812a920a2

**Comment by fattanasio** [comment]
Hi, i have same problem to show a preview of an images captured with cordova-plugin-camera. This photo is in file://etc....
Can't I preview this file?
Thank you, bye

**Comment by lovelyelfpop** [comment]
An other solution
https://github.com/apache/cordova-plugin-file/pull/296

This PR solves this by allowing access to cdvfile://localhost/bundle/www/cordova.js using the url: https://xxx.com/cdvfile/bundle/www/cordova.js

**Comment by ptorrent** [comment]
Hello,

Is it possible to write a file (ex: an image) into the context root directory (where is index.html) and read it with file:// ?

Thanks for your help

**Comment by lovelyelfpop** [comment]
@ptorrent  Assets directory is readonly.

**Comment by ptorrent** [comment]
So what is the benefit of this plugin  ?

**Comment by lovelyelfpop** [comment]
cordova-ios@6.0.0+ supports custom scheme, you can use url like `myscheme://localhost/filename.ext` to access a local file.
And there is a function to convert a file url to a  custom scheme url. 
For example, `window.WkWebView.convertFilePath('file:///var/mobile/Containers/Data/Application/{UUID}/tmp/1.jpg')` gets `cdv://localhost/_app_file_/var/mobile/Containers/Data/Application/{UUID}/tmp/1.jpg`, img element can be loaded with this url.
Don't forget to edit Content-Security-Policy in html to support `myscheme:`

**Comment by ptorrent** [comment]
I assume "tmp" means the file is not persistent? On android cdvfile works fine. WkWebView doesn't support schema anymore.

How would creating my own schema solve this problem? Why would I need to create new schemas? Does it make sense?

Is the solution proposed by lovelyelfpop the only solution to make it work on android / ios?

Thanks for your support !

**Comment by lovelyelfpop** [comment]
All directory(e.g. Document, Library) under `file:///var/mobile/Containers/Data/Application/{UUID}/`, not just `tmp`

**Comment by ptorrent** [comment]
thanks you for your clarification !

**Comment by Lindsay-Needs-Sleep** [comment]
> cordova-ios@6.0.0+ supports custom scheme, you can use url like `myscheme://localhost/filename.ext` to access a local file.
> And there is a function to convert a file url to a custom scheme url.
> For example, `window.WkWebView.convertFilePath('file:///var/mobile/Containers/Data/Application/{UUID}/tmp/1.jpg')` gets `cdv://localhost/_app_file_/var/mobile/Containers/Data/Application/{UUID}/tmp/1.jpg`, img element can be loaded with this url.
> Don't forget to edit Content-Security-Policy in html to support `myscheme:`

This worked for me!
(Worked for videos too.)

**Comment by signalpoint** [comment]
While working through a related problem, I came across this issue. Thank you @Lindsay-Needs-Sleep for sending me in the right direction.

I was receiving this error:

`toDataUrl() SecurityError: The operation is insecure.`

Adding this to `config.xml` fixed it:

```
<preference name="scheme" value="app" />
<preference name="hostname" value="localhost" />
```

After that (and after running `cordova ios prepare`), I ran into this error:

`Not allowed to load local resource: file:///Users/.../foo.jpg`

I was able to fix that in my custom .js, for example:

```
var myUri = "file:///Users/.../foo.jpg";
var fixedUri = window.WkWebView.convertFilePath(myUri);
```
