### ISSUE TITLE
Cross-origin error from canvas.ctx.getImageData()

### ISSUE THREAD

**Issue by shubckin** [oracle/cordova-plugin-wkwebview-file-xhr#47]
When i call method getImageData from canvas, i get error:
"Unable to get image data from canvas because the canvas has been tainted by cross-origin data".
Example to reproduce this error:
    function testCanvas(src) {
        var canvas = document.createElement("canvas");
        var img = new Image();
        img.addEventListener("load", function () {
            canvas.getContext("2d").drawImage(img, 0, 0, img.width, img.height, 0, 0, canvas.width, canvas.height);
            canvas.getContext("2d").getImageData(0,0,img.width, img.height);
            canvas.toDataURL();
        });
        img.setAttribute("src", src);
    }

**Comment by manish2788** [comment]
@shubckin We will analyse the reported the issue and get back to you.

**Comment by ragcsalo** [comment]
I have the same problem.... also all my Javascript files that are included in the main index.html are treated as cross-origin resources, therefore I get no detailed Javascript errors.

I hope there will be a solution for all this nightmare soon. :-)

**Comment by manish2788** [comment]
@ragcsalo We are looking into the issue. Will update you by next week.

**Comment by manish2788** [comment]
@shubckin I am not able to reproduce the issue. Can you please verify the same using latest version of plugin.
