### ISSUE TITLE
Debugging a result with status -1

### ISSUE THREAD

**Issue by velochy** [oracle/cordova-plugin-wkwebview-file-xhr#5]
I am making a post request and it comes back to the webview as Status: -1.
I would really like to know what is going wrong but I have no clue even where to start. Normally, I would look at safari Resources tab and get the request headers + server response. Any way I can access this info even when this plugin is in place?

**Comment by gvanmat** [comment]
The NativeXHRLogging preference set to "full" will give you detail logging of the request.  See:
https://github.com/oracle/cordova-plugin-wkwebview-file-xhr#configuration
