### ISSUE TITLE
The certificate for this server is invalid. 

### ISSUE THREAD

**Issue by PawelGIX** [oracle/cordova-plugin-wkwebview-file-xhr#54]
The certificate for this server is invalid. You might be connecting to a server that is pretending to be...

My server: https://mrecepta.oneplusone.pl 
Any idea why i get this error. I also get tis error on another server & domain https://mrecepta.pl

**Comment by manish2788** [comment]
@PawelGIX Seems to be issue with server setting which you are trying to connect. I don't see any issue from plugin's end. Can you furnish more detail about your setup (Cordova version etc.)

**Comment by manish2788** [comment]
Closing this issue as no response received from issue filer.
