### ISSUE TITLE
cordova-ios 6 support

### ISSUE THREAD

**Issue by breautek** [oracle/cordova-plugin-wkwebview-file-xhr#55]
Hi there,

Cordova has released `cordova-ios@6` which implements the `WKWebView` making their [wkwebview](https://github.com/apache/cordova-plugin-wkwebview-engine) plugin obsolete.

But for users who still need to use the `file://` scheme, this plugin is still necessary if you need to use XHR to local `file://` paths.

I would advise making a minor/patch release that limits version 2.x to cordova-ios@5.x, and a new major release that expects cordova-ios@6 and removes the wkwebview engine plugin dependency.

I think this is necessary to solve https://github.com/apache/cordova-ios/issues/883

**Comment by manish2788** [comment]
@breautek Thanks Norman. We are woking on this. We will soon be broadcasting our next course of actions.

**Comment by ej-dunne** [comment]
@breautek just so you know, I forked this repo and simply removed the wkwebview plugin dependency from the plugin.xml file (line 30) and that seems to have worked. I'm not sure if there will be any other issues due to the small change I made though, so I am still waiting for and new release here, but that got things working with cordova-ios 6.0.0 for now at least

**Comment by nickredding** [comment]
It seems to me the Cordova iOS 6.0.0 release addresses the file:// issue when loading files from the main bundle but not the cross-origin issue when accessing remote endpoints (this is the second bullet point under "About the cordova-plugin-wkwebview-file-xhr") so this plugin will still be required for apps that need to access arbitrary remote endpoints that are configured to disallow requests from the null origin.

**Comment by manish2788** [comment]
We are working on validating certain features of this plugin. We will revert with updates soon.

**Comment by globules-io** [comment]
https://github.com/globules-io/cordova-plugin-ios-xhr

**Comment by ppetree** [comment]
To add to this, if you're using any multi-page framework such as Framework7 or even an old version of JQM, you will need this plugin.  With CLI 10 you can't build with this plugin and you're dead in the water without it.

**Comment by AraHovakimyan** [comment]
@breautek You can use for Cordova iOS 6.0.0, 6.1.0

cordova plugin add https://github.com/AraHovakimyan/cordova-plugin-wkwebviewxhrfix

It works fine for me.

**Comment by jpike88** [comment]
@manish2788 'validating certain features'... what? It's literally one line in the config.xml you remove and voila it works. And now it's mid-Sept, almost 2 months later. Corporate doublespeak nonsense.

**Comment by manish2788** [comment]
@jpike88 We have other features as well which requires release. Cordova-ios6 support is one of the feature. We have planned release next week.

**Comment by manish2788** [comment]
Latest Plugin Version 3.0.0 takes care of cordova-ios6 support.

**Comment by ygyg70** [comment]
I am still getting the same issue with cordova-ios6.1.1
https://github.com/AraHovakimyan/cordova-plugin-wkwebviewxhrfix works for me

**Comment by AraHovakimyan** [comment]
Can you explain the issue?
The plugin you mentioned "https://github.com/AraHovakimyan/cordova-plugin-wkwebviewxhrfix" can't solve your problem or a problem is with Oracle plugin?

**Comment by AraHovakimyan** [comment]
> I am still getting the same issue with cordova-ios6.1.1
> https://github.com/AraHovakimyan/cordova-plugin-wkwebviewxhrfix works for me

Can you explain the issue?
The plugin you mentioned "https://github.com/AraHovakimyan/cordova-plugin-wkwebviewxhrfix" can't solve your problem or a problem is with Oracle plugin?

**Comment by ancliffo** [comment]
> I am still getting the same issue with cordova-ios6.1.1 https://github.com/AraHovakimyan/cordova-plugin-wkwebviewxhrfix works for me

This was the only thing that worked for me, too.
