### ISSUE TITLE
Unable to post message to file://. Recipient has origin null.

### ISSUE THREAD

**Issue by w4ugit** [oracle/cordova-plugin-wkwebview-file-xhr#56]
I have an application written on vue. It worked until I switched to WkWebView. Then I started to get this error - Unable to post message to file: //. Recipient has origin null. Installing your plugin did not help. Do I have to do anything else in my code?

**Comment by marcossantana** [comment]
I'm getting the same error. Someone fixed it?

**Comment by manish2788** [comment]
@w4ugit What version of cordova you are using? Can you furnish more detail about your project setup.

**Comment by marcossantana** [comment]
@manish2788 can we talk about this? using email or skype? i can pay from your support.

**Comment by manish2788** [comment]
@marcossantana Please share the detail of your setup.

**Comment by marcossantana** [comment]
I have some specifics features. If it is possible, i would talk privating with you.

**Comment by ej-dunne** [comment]
I had the same problem, searched everywhere and couldn't find an answer, but this worked. Either create a plugin that does the following or add it to your existing code

Add the following to your header:

#import <WebKit/WebKit.h>
#import <Cordova/CDV.h>

Then the following to your code:

NSLog(@"Updating webview to allow local file access");
WKWebView *wkWebView = (WKWebView *) self.webViewEngine.engineWebView
[wkWebView.configuration.preferences setValue:@YES forKey:@"allowFileAccessFromFileURLs"];

**Comment by manish2788** [comment]
Closing this issue as not response received from issue filer.
