### ISSUE TITLE
Cookies not stored after app relaunch

### ISSUE THREAD

**Issue by AlekseyPimenov** [oracle/cordova-plugin-wkwebview-file-xhr#57]
I use that plugin to have ability to use 'Set-Cookie' header that required my app. All works fine, (thanks for that a lot) except one thing.
But after relaunch app all cookies looks like not stored and user should login again. 
Is there way to store it?

**Comment by manish2788** [comment]
Hi @AlekseyPimenov , Your SDK should provide you a way to store the cookie, this plugin just resolves couple of issue in WKwbeview as mentioned in the description.
