### ISSUE TITLE
Not working on iOS 14

### ISSUE THREAD

**Issue by idoodler** [oracle/cordova-plugin-wkwebview-file-xhr#59]
This plugin is not working on iOS 14 devices. Tested on my iPhone 11 Pro running the second Beta of iOS 14.

I am not sure how I should debug this. By using Wireshark I could see a lots of `OPTIONS` requests. The log of the Browsers Network monitor is not really useful. I will monitor this and keep this issue updated. It may be an issue on Apples side.

Anyone has similar issues?

**Comment by p7161** [comment]
Same issue. Just not work in iOS 14

**Comment by manish2788** [comment]
@idoodler We are working on validating this behavior. We will revert with the updates soon.

**Comment by manish2788** [comment]
@idoodler I was successfully able to validate the plugin over iOS 14 Beta without any issue. If you are still facing issue can you share a sample app which can be verified at my end. Moreover can you provide cordova, cordova-ios version of your setup.

**Comment by manish2788** [comment]
Closing issue due to lack of response.
