### ISSUE TITLE
Newer XCode restricts webView to be called only from main thread

### ISSUE THREAD

**Issue by velochy** [oracle/cordova-plugin-wkwebview-file-xhr#6]
XCode shows the following runtime errors:
[WKScriptMessage body] must be used from main thread only
[WKScriptMessage webView] must be used from main thread only
This is a restriction since iOS 11 (so it is relatively recent)

Offending lines are 407-409 of CDVWKWebViewFileXhr.m

**Comment by gvanmat** [comment]
Thanks for reporting the issue.

**Comment by gvanmat** [comment]
@velochy Checked in a fix for iOS 11.  Please help me verify the fix.
