### ISSUE TITLE
not working with xml request

### ISSUE THREAD

**Issue by satish0563** [oracle/cordova-plugin-wkwebview-file-xhr#60]
I am calling API with XML request but it goes inside  exception delivering event

**Comment by manish2788** [comment]
@satish0563 Can you please elaborate the issue you are facing. What do you mean by calling API? which API you intend to call.

**Comment by manish2788** [comment]
Closing this issue due to lack of response. Please log another issue with detail and logs if you need any assistance.

**Comment by franknoel** [comment]
We had a similar issue, our `XMLHttpRequest` request always had the `text` type on iOS.
We used the following code to force the request type:

```
var req = new XMLHttpRequest();
req.responseType = 'document';
req.overrideMimeType('text/xml');
```
