### ISSUE TITLE
Images are still not showing in from app img folder

### ISSUE THREAD

**Issue by Karanveer-flymedia** [oracle/cordova-plugin-wkwebview-file-xhr#61]
Hii dear, 
can you please help me i am stucked just because of this issue... images are still not showing in app after installing this plugin, i am using ionic1 and not able to upload my app on appstore please help me...

**Comment by manish2788** [comment]
@Karanveer-flymedia Can you share detail of your setup and how you are configuring the file path.

**Comment by Karanveer-flymedia** [comment]
@manish2788 - it's done from my side this was because of my mistake... thanks for reply...
