### ISSUE TITLE
Spaces in url's gives issues

### ISSUE THREAD

**Issue by Ruud-cb** [oracle/cordova-plugin-wkwebview-file-xhr#63]
Hi,
We have a lot of svg's that, unfortunately, contain spaces in there file names (loaded from external packages). This results in 404 not found errors.
In this section I added some code https://github.com/oracle/cordova-plugin-wkwebview-file-xhr/blob/master/src/ios/CDVWKWebViewFileXhr.m#L132

```
    uri = [uri stringByReplacingOccurrencesOfString:@" "
                                    withString:@"%20"];
```

Perhaps you want to add this and some other modifications.

**Comment by manish2788** [comment]
I would recommend you to use encodeURI api in javascript to handle filename with spaces.
