### ISSUE TITLE
SOAP

### ISSUE THREAD

**Issue by fpardigon** [oracle/cordova-plugin-wkwebview-file-xhr#64]
Hello,

Do you know if the cordova-plugin-wkwebview-file-xhr plug-in works with SOAP requests?

I am having issues with the SOAP request and the module.
It seems that the data and some information of the header are not transmitted.

**Comment by manish2788** [comment]
@fpardigon Can you provide a sample app our briefly describe your configuration and platform details.

**Comment by manish2788** [comment]
Closing the thread due to lack of response.
