### ISSUE TITLE
Support For Synchronous Requests

### ISSUE THREAD

**Issue by AareFabrik** [oracle/cordova-plugin-wkwebview-file-xhr#65]
This plugin apparently does not support synchronous XHRequests.

Is this planned to be implemented?

I depend on a third party library which is using following synchronous Request:

```javascript
var req = new XMLHttpRequest;
req.addEventListener("load", function(r) {
    ...
});
t.addEventListener("error", function(t) {
    ...
});
t.open("GET", url, false); // false is for async boolean
```

Or any hints how to do this?

**Comment by facetbarcelona** [comment]
The following plugin has done the trick for me (I do synchronous requests for local resources):
https://github.com/TheMattRay/cordova-plugin-wkwebviewxhrfix

I hope this helps.

**Comment by AareFabrik** [comment]
Hello, thanks for the answer. We finally finished with the same fork as you mentioned. Hopefully it helps others to find it quicker.

**Comment by manish2788** [comment]
@AareFabrik We don't have any plan to support synchronous requests for local resources in near future considering Synchronous XHR is now in deprecation state.
