### ISSUE TITLE
Possibility to handle remote image sources with this plugin

### ISSUE THREAD

**Issue by Gr33nW33n** [oracle/cordova-plugin-wkwebview-file-xhr#66]
Hello,

is it possible, to also handle image sources (img src="...") and css background images (url("...")) with this plugin?

I'm asking because at the moment I'm using this plugin to handle all of our xhr calls to be called from native, so that our cookies are sent with the xhr call on iOS.

We also have image sources that needs to be sent with a cookie included, but with the iOS 14 Intelligent Tracking Prevention change, the cookie isn't sent anymore.

Thanks in advance & BR
Jakob

**Comment by manish2788** [comment]
@Gr33nW33n This plugin makes use  XHR requests to resolve the WKWebview issues. You request cannot be incorporated.

**Comment by iwan-uschka** [comment]
Hey @Gr33nW33n , have you found a solution here? I also need to load assets that are only accessible by sending a valid session cookie. I can't make it work on iOS 12. Does it work for you on iOS 12?

**Comment by Gr33nW33n** [comment]
Hey @iwan-uschka, 
I actually fetched the images via ajax calls, so the session cookies were sent with this plugin.

BR

**Comment by iwan-uschka** [comment]
Thx @Gr33nW33n for getting back on this one.
Your solution will probably work for data that
- can be parsed (JSON for instance)
- can be added to the DOM as a blob (image for instance)
- doesn't need to be streamed like audio or video (If I got that right you can't get access to the data during loading process)

I will checkout https://github.com/aporat/cordova-plugin-fetch/issues/23 next. Maybe i can make this work.
