### ISSUE TITLE
This plugin makes Android give an error

### ISSUE THREAD

**Issue by martijnmichel** [oracle/cordova-plugin-wkwebview-file-xhr#72]
After having installed this plugin my app started working on iOS (loading mp3 files) but stopped working for android giving an error: 

I/chromium: [INFO:CONSOLE(535)] "Fetch API cannot load file:///android_asset/www/statics/sound/piano/C6.mp3. URL scheme "file" is not supported.", source: file:///android_asset/www/js/vendor.js (535)

**Comment by manish2788** [comment]
@martijnmichel This plugin is targeted to be used only on iOS platform. It is not supposed to be installed on an android app.

**Comment by martijnmichel** [comment]
How can I install it on iOS only?
