### ISSUE TITLE
Crash app when send ajax request with FormData with file size ~40MB

### ISSUE THREAD

**Issue by taxuangiao** [oracle/cordova-plugin-wkwebview-file-xhr#75]
At this moment, all requests are intercepted by this plugin.
However, when i send an ajax request with FormData with file size ~40MB, my application is crashed.
These is log conent

> XPC error talking to pkd: Connection interrupted

> <SOServiceConnection: 0x2813036c0>: XPC connection interrupted

> Received memory pressure event 2 vm pressure 0

> [shim] BKSProcessAssertion "ConnectionTerminationWatchdog" initialized with invalid pid

> Error acquiring assertion: <NSError: 0x281de2580; domain: RBSAssertionErrorDomain; code: 2; reason: "Specified target process does not exist">

Can someone please help me to fix this issue?
Thank you so much.

**Comment by manish2788** [comment]
@taxuangiao We will look into the issue and get back to you at earliest.

**Comment by manish2788** [comment]
@taxuangiao We are not able to reproduce this issue. Can you share a sample app demonstrating the issue being reported by you.

**Comment by manish2788** [comment]
Closing the issue due to lack of response.
