### ISSUE TITLE
formdata.set not working with file and name property already set

### ISSUE THREAD

**Issue by FrankStierle** [oracle/cordova-plugin-wkwebview-file-xhr#77]
We have problems with generated api code from swagger, like that:

formData.append("name", file);

Here the filename is not provided bu file is a File Object extended from Blob and has the filename already in the "name"  property.

This will work when you change the code in the formdata-polyfill.js line 116:

From:

  if (value && Blob.prototype.isPrototypeOf(value))

To:

  if (value && !value.name && Blob.prototype.isPrototypeOf(value))

**Comment by manish2788** [comment]
@FrankStierle Can you share a sample cordova app demonstrating the above mentioned issue?
