### ISSUE TITLE
XHR load local file synchronization

### ISSUE THREAD

**Issue by taxuangiao** [oracle/cordova-plugin-wkwebview-file-xhr#78]
Dear @All,
At this moment, when use this plugin, I cannot load local file via XHR synchronization as below:
`xhttp.open("GET", filePath, false);
xhttp.send(null);
var text = xhttp.responseText;
`
Is this issue?
Thank you so much.

**Comment by manish2788** [comment]
@taxuangiao No such issue exists as reported by you. Plugin works fine for synchronous request as well.

**Comment by taxuangiao** [comment]
@manish2788 Thanks. However, I retry with synchronous XHR request and It is not OK. But I update to asynchronous XHR request, I could load file content. So please check again.

**Comment by manish2788** [comment]
@taxuangiao Can you please share a sample cordova app demonstrating the issue you are facing.

**Comment by taxuangiao** [comment]
@manish2788 there are source code to load file
  var xhr = new XMLHttpRequest();
  xhr.open("GET", "js/test.txt", false);
  xhr.send();
  var data = xhr.responseText;
  if (data) {
    alert(data);
  } else {
    alert("ERROR");
  }
the result is show alert "ERROR"

**Comment by manish2788** [comment]
@taxuangiao Please go through https://javascript.info/xmlhttprequest to understand how to create an XMLHttpRequest request and get a response. No issue with the plugin.

**Comment by taxuangiao** [comment]
@manish2788 , with above  code, I tried remove this plugin and build on cordova-ios@4 (UIWebView) and it is OK. I think the plugin not support synchronous XHR request.

**Comment by gvanmat** [comment]
On the ios side the http request, response is synchronous but the
communication with the plugin is asyc. The client registers a callback
handler. At the time this was originally development, Js es6 await/async
was not an option. It might be possible now for the send to return a
promise and the client could call await xhr.send(). Kind of a JS impl
restriction.
