### ISSUE TITLE
Polyfill not injected ! Plugin not added properly.

### ISSUE THREAD

**Issue by MoAsmar** [oracle/cordova-plugin-wkwebview-file-xhr#8]
I installed the plugin but it seems that something is wrong, because Polyfill was not injected on app run and the app is not working anymore and the problem in loading files through xhr is still.

**Comment by gvanmat** [comment]
There is a known issue with iOS 11. Are you by chance using 11.

**Comment by gvanmat** [comment]
No followup in a couple weeks.  Closing the issue.

**Comment by brunoborges** [comment]
Hey @gvanmat you may want to set a template for issues, so people submit required information such as environment, versions, etc. [See this](https://github.com/blog/2111-issue-and-pull-request-templates).

**Comment by MoAsmar** [comment]
Hey gvanmat, I am using IOS 11 yes, what is the known issue and what is its fix ?

**Comment by gvanmat** [comment]
Failure to run under iOS 11 was reported in issue #6. We released v2.0.0 of the plugin 9/20.  xcode for iOS 11 was released 9/19.

The fix is still being worked but will be in the v2.1.0 release of the plugin.

**Comment by MoAsmar** [comment]
Ok thanks I used another webview for now.

**Comment by gvanmat** [comment]
@MoAsmar Checked in a fix for issue #6 and #4.  Please help me verify.
