### ISSUE TITLE
Just a precision about the JS code

### ISSUE THREAD

**Issue by nbrignol** [oracle/cordova-plugin-wkwebview-file-xhr#81]
Not a problem, just a precision : 
The "responseText" will be available on the "this" in the event callback only, and no more in the event.target itself (like it is in classic XHR). 

I guess you should note it in the doc.
Thank about that plugin BTW !

    xhr.addEventListener("loadend", function(evt) {
       //var data = evt.target.responseText; //<-- this will not work with the plugin 
       var data = this.responseText; //<-- this works
       document.getElementById("myregion").innerHTML = data;
     });

**Comment by manish2788** [comment]
Thanks @nbrignol . We will make a note of your feedback.
