### ISSUE TITLE
onprogress action

### ISSUE THREAD

**Issue by iljaverba00** [oracle/cordova-plugin-wkwebview-file-xhr#82]
Hi. My app downloads zip archives. When uploading, I need to track the progress. 
This question has already been raised in: https://github.com/oracle/cordova-plugin-wkwebview-file-xhr/issues/7
Is a solution possible in the near future?

**Comment by manish2788** [comment]
@iljaverba00 Currently we are not considering it as a feasible fix. No planned solution for this in near future.
