### ISSUE TITLE
still getting cors issue

### ISSUE THREAD

**Issue by martijnmichel** [oracle/cordova-plugin-wkwebview-file-xhr#84]
having fixed the cors issue half a year ago, after reinstalling my cordova app on my development station I am represented with this annoying bug. Using this plugin doesn't fix it.

On iOS 14.6, with cordova-ios@6.2.0

```
cross origin requests are only supported for HTTP.
vendor.js:1046 Cross origin requests are only supported for HTTP.
vendor.js:1046 Fetch API cannot load file:///private/var/containers/Bundle/Application/BDC5D48C-F2A2-4907-BE39-73E8DD943F85/Sonid.app/www/statics/sound/piano/C7.mp3 due to access control checks.
```

**Comment by manish2788** [comment]
Can you please provide a sample app to showcase this issue?

**Comment by manish2788** [comment]
@martijnmichel Can you please provide a sample app to showcase this issue?

**Comment by manish2788** [comment]
Closing the issue due to lack of response.
