### ISSUE TITLE
Unable to send form-data only for iOS

### ISSUE THREAD

**Issue by bhandaribhumin** [oracle/cordova-plugin-wkwebview-file-xhr#88]
When sending a form-data through POST call, receiving **Unable to get name from form-data** response.
When I debugged this problem, it was found that this issue is happening due to **content-disposition**, API expects **Content-Disposition** but the app is sending **content-disposition** (please observe the case) [here](https://github.com/oracle/cordova-plugin-wkwebview-file-xhr/blob/master/src/www/ios/formdata-polyfill.js#L345).

Solution provided by [Mulesoft](https://help.mulesoft.com/s/article/Unable-to-get-name-from-form-data#:~:text=SOLUTION,by%20the%20Mulesoft%20product%20team.) is here.

Solution: Changing the content-disposition in small cases makes the API work.

This is an important plugin for our organization please help.
CC: @manish2788

**Comment by manish2788** [comment]
@bhandaribhumin 
Acknowledged. We will look into the issue and get back to you ASAP.

**Comment by bhandaribhumin** [comment]
Thank you @manish2788
