### ISSUE TITLE
XMLHttpRequest.onerror is called erroneously if status code >= 400 

### ISSUE THREAD

**Issue by vbraun** [oracle/cordova-plugin-wkwebview-file-xhr#9]
The onerror callback should only be called on network-level errors; If there is a response then, by definition, there was no network level error. The value of the status code is irrelevant. More discussion is at https://stackoverflow.com/questions/10584318/when-should-xmlhttprequests-onerror-handler-fire

    if (payload.response.statusCode === 0 || payload.response.statusCode >= 400)
      reqContext.dispatchProgressEvent("error", respSize);

For the record, angularjs registers an onerror handler that correctly discards any results. So all $http calls that return a statusCode >= 400 now look like network errors.

**Comment by gvanmat** [comment]
It's simulating the same behavior for a native JS XMLHttpRequest.  If you went after a resource that was not found or a 500 server except, the XMLHttpRequest fires a "error" event.

**Comment by vbraun** [comment]
Well a 404 doesn't, for example open the console on this page and run:
~~~~
var xmlhttp = new XMLHttpRequest(),
  method = 'GET',
  url = 'https://github.com/foo/bar';

xmlhttp.open(method, url, true);
xmlhttp.onerror = function () {
  console.log("** An error occurred during the transaction");
};
xmlhttp.send();
~~~~
does NOT call onerror.

A CORS error will trigger onerror though, i.e. if you run the same snippet from the console on a different website then it will be called.

**Comment by gvanmat** [comment]
I  just pushed in a fix. Please uninstall and re-install the plugin from the master to verify the fix:

cordova plugin remove cordova-plugin-wkwebview-file-xhr
cordova plugin add https://github.com/oracle/cordova-plugin-wkwebview-file-xhr.git
